export const PERMISSIONS = {
  USER: {
    LIST: 'USER_LIST',
    CREATE: 'USER_CREATE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
  },
  CATEGORY: {
    LIST: 'CATEGORY_LIST',
    CREATE: 'CATEGORY_CREATE',
    UPDATE: 'CATEGORY_UPDATE',
    DELETE: 'CATEGORY_DELETE',
  },
  LEARNING_PATH: {
    LIST: 'LEARNING_PATH_LIST',
    CREATE: 'LEARNING_PATH_CREATE',
    UPDATE: 'LEARNING_PATH_UPDATE',
    DELETE: 'LEARNING_PATH_DELETE',
  },
  ROLE: {
    LIST: 'ROLE_LIST',
    CREATE: 'ROLE_CREATE',
    UPDATE: 'ROLE_UPDATE',
    DELETE: 'ROLE_DELETE',
    ASSIGN_PERMISSION: 'ROLE_ASSIGN_PERMISSION',
  },
} as const;

export enum PermissionOperator {
  AND = 'AND',
  OR = 'OR',
}
